language "C++"
cppdialect "C++17"
files 
{
  "src/**.h",
  "src/**.cpp",
}

vpaths
{
  ["Misc"] = 
  {
    "src/DgAssert.h",
    "src/DgParser_INI.h",
    "src/DgStringFunctions.h",
    "src/DgTimer.h",
    "src/DgTypes.h",
    "src/DgIDManager.h",
    "src/DgEndian.h"
  },
  ["Misc/io"] = 
  {
    "src/DgStream.h",
    "src/DgMemoryStream.h",
    "src/DgFileStream.h",
  },
  ["Misc/impl"] = 
  {
    "src/impl/DgStringFunctions.cpp",
    "src/impl/DgAssert.cpp",
    "src/impl/DgParser_INI.cpp",
    "src/impl/DgTimer.cpp",
    "src/impl/DgEndian.cpp",
    "src/impl/DgStream.cpp",
    "src/impl/DgMemoryStream.cpp",
    "src/impl/DgFileStream.cpp"    
  },
  ["Math"] = 
  { 
    "src/DgFixedPoint.h",
    "src/DgMath.h",
    "src/DgMatrix.h",
    "src/DgRNG_Local.h",
    "src/DgRNG_Global.h",
    "src/DgBoundedSND.h",
    "src/DgQueryCommon.h"
  },
  ["Math/impl"] = 
  {
    "src/impl/Dgmath.cpp",
    "src/impl/DgRNG.cpp",
    "src/impl/DgRNG_Base.h",
    "src/impl/DgMath_impl.h",
    "src/impl/DgMatrix_generic.h",
    "src/impl/DgAABB_generic.h",
    "src/impl/DgCPQuery.h",
    "src/impl/DgFIQuery.h",
    "src/impl/DgFPCQuery.h",
    "src/impl/DgFPCQueryHypersphereHypersphere.h",
    "src/impl/DgFPCQueryHypersphereLine.h",
    "src/impl/DgFPCQueryPointHypersphere.h",
    "src/impl/DgHyperSphere_generic.h",
    "src/impl/DgLine_generic.h",
    "src/impl/DgQueryFrustumSphere.h",
    "src/impl/DgQueryLineHypersphere.h",
    "src/impl/DgQueryLineLine.h",
    "src/impl/DgQueryLinePlane.h",
    "src/impl/DgQueryPointLine.h",
    "src/impl/DgQueryPointPlane.h",
    "src/impl/DgQueryPointRay.h",
    "src/impl/DgQueryPointSegment.h",
    "src/impl/DgQueryRayLine.h",
    "src/impl/DgQueryRayPlane.h",
    "src/impl/DgQueryRayRay.h",
    "src/impl/DgQueryRayTriangle.h",
    "src/impl/DgQuerySegmentHypersphere.h",
    "src/impl/DgQuerySegmentLine.h",
    "src/impl/DgQuerySegmentPlane.h",
    "src/impl/DgQuerySegmentRay.h",
    "src/impl/DgQuerySegmentSegment.h",
    "src/impl/DgRay_generic.h",
    "src/impl/DgSegment_generic.h",
    "src/impl/DgTriangle_generic.h",
    "src/impl/DgVector_generic.h",
    "src/impl/DgTIQuery.h",
    "src/impl/DgR3Matrix_generic.h",
    "src/impl/DgR3Vector_generic.h",
    "src/impl/DgR2Matrix_generic.h",
    "src/impl/DgR2Vector_generic.h",
    "src/impl/DgVector2_generic.h"
  },
  ["Math/R2"] = 
  {
    "src/DgR2AABB.h",
    "src/DgR2Disk.h",
    "src/DgR2Line.h",
    "src/DgR2Matrix.h",
    "src/DgR2Polygon.h",
    "src/DgR2Ray.h",
    "src/DgR2Regression.h",
    "src/DgR2Segment.h",
    "src/DgR2Triangle.h",
    "src/DgR2Vector.h",
    "src/DgR2Vector_ancillary.h",
  },
  ["Math/R3"] = 
  {
    "src/DgR3AABB.h",
    "src/DgR3Frustum.h",
    "src/DgR3Line.h",
    "src/DgR3Matrix.h",
    "src/DgR3OBB.h",
    "src/DgR3Plane.h",
    "src/DgR3Quaternion.h",
    "src/DgR3Ray.h",
    "src/DgR3Rectangle.h",
    "src/DgR3Segment.h",
    "src/DgR3Sphere.h",
    "src/DgR3Triangle.h",
    "src/DgR3Vector.h",
    "src/DgR3Vector_ancillary.h",
    "src/DgR3VQS.h",
    "src/DgR3ZCylinder.h"
  },
  ["Math/R2/Queries"] = 
  {
    "src/DgR2QueryDiskDisk.h",
    "src/DgR2QueryDiskLine.h",
    "src/DgR2QueryLineLine.h",
    "src/DgR2QueryPointDisk.h",
    "src/DgR2QueryPointLine.h",
    "src/DgR2QueryPointRay.h",
    "src/DgR2QueryPointSegment.h",
    "src/DgR2QueryRayLine.h",
    "src/DgR2QueryRayRay.h",
    "src/DgR2QuerySegmentLine.h",
    "src/DgR2QuerySegmentRay.h",
    "src/DgR2QuerySegmentSegment.h"
  },
  ["Math/R3/Queries"] = 
  {
    "src/DgR3QueryFrustumSphere.h",
    "src/DgR3QueryLineLine.h",
    "src/DgR3QueryLinePlane.h",
    "src/DgR3QueryLineSphere.h",
    "src/DgR3QueryPointLine.h",
    "src/DgR3QueryPointPlane.h",
    "src/DgR3QueryPointRay.h",
    "src/DgR3QueryPointSegment.h",
    "src/DgR3QueryPointSphere.h",
    "src/DgR3QueryPointZCylinder.h",
    "src/DgR3QueryRayLine.h",
    "src/DgR3QueryRayPlane.h",
    "src/DgR3QueryRayRay.h",
    "src/DgR3QueryRayTriangle.h",
    "src/DgR3QueryRectangleLine.h",
    "src/DgR3QueryRectanglePoint.h",
    "src/DgR3QueryRectangleRay.h",
    "src/DgR3QueryRectangleSegment.h",
    "src/DgR3QueryRectangleSphere.h",
    "src/DgR3QuerySegmentLine.h",
    "src/DgR3QuerySegmentPlane.h",
    "src/DgR3QuerySegmentRay.h",
    "src/DgR3QuerySegmentSegment.h",
    "src/DgR3QuerySegmentSphere.h",
    "src/DgR3QuerySphereSphere.h"
  },
  ["Collections"] = 
  {
    "src/DgMap_AVL.h",
    "src/DgSet_AVL.h",
    "src/DgCircularDoublyLinkedList.h",
    "src/DgDoublyLinkedList.h",
    "src/DgDynamicArray.h",
    "src/DgHyperArray.h",
    "src/DgOpenHashTable.h",
    "src/DgPair.h",
    "src/DgStaticArray.h",
    "src/DgVariableArray2D.h"
  },
  ["Collections/impl"] = 
  {
    "src/impl/DgAVLTree_Common.h",
    "src/impl/DgContainerBase.cpp",
    "src/impl/DgContainerBase.h",
    "src/impl/DgHashTable.cpp",
    "src/impl/DgPoolSizeManager.h",
    "src/impl/DgPoolSizeManager.cpp"
  }
}